server:
  port: 8393
spring:
  jpa:
    show-sql: true
logging:
  level:
    org.hibernate.SQL: debug
out-focusing:
  access-token-secret-key: "${ACCESS_TOKEN_SECRET_KEY}"
  refresh-token-secret-key: "${REFRESH_TOKEN_SECRET_KEY}"