spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always